{{- if .Values.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nodejs-server.fullname" . }}-secrets
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
data:
  {{- with .Values.secrets.data -}}
  {{- range $key, $value := . }}
  {{ $key | upper }}: {{ $value | b64enc | quote }}
  {{- end -}}
  {{- end -}}
{{- end -}}