{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs-server.fullname" . }}-svc
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "nodejs-server.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "nodejs-server.selectorLabels" . | nindent 4 }}
  {{- with .Values.service }}
  type: {{ .type | default "ClusterIP" }}
  ports:
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      {{- if eq .type "NodePort" }}
      nodePort: {{ .nodePort | default 30000 }}
      {{- end }}
  {{- end -}}
{{- end -}}